episodedetails:
  - title: '{title}'
  - showtitle: '{uploader}'
  - season:
      converter:
        data_type: 'date'
        input_f: '%Y%m%d'
        output_f: '%Y'
      value: '{upload_date}'
  - episode:
      converter:
        data_type: 'date'
        input_f: '%Y%m%d'
        output_f: '%m%d'
      value: '{upload_date}'
  - year:
      converter:
        data_type: 'date'
        input_f: '%Y%m%d'
        output_f: '%Y'
      value: '{upload_date}'
  - aired:
      converter:
        data_type: 'date'
        input_f: '%Y%m%d'
        output_f: '%Y-%m-%d'
      value: '{upload_date}'
  - plot: '{description}'
  - genre: '{extractor_key}'
  - uniqueid:
      attrs:
        default: 'true'
        type: 'nebula'
      value: '{channel_id}'
