episodedetails:
  - genre!: "{categories}"
  - actor>name!: "{cast}"
  - really>nested>actor>name>list!: "{cast}"
  - this>should>be>invalid: "{upload_date}"
  - normal: "{upload_date}"
  - converted>date:
      convert: "date"
      input_f: "%Y%m%d"
      output_f: "%Y-%m-%d"
      value: "{upload_date}"
  - nested>date!:
      convert: "date"
      input_f: "%Y%m%d"
      output_f: "%Y-%m-%d"
      value: "{nested_dates}"
