episodedetails:
  - title: '{title}'
  - showtitle: '{uploader}'
  - uniqueid:
      attr:
        type: 'youtubetab'
        default: "true"
      value: '{id}'
  - plot: '{description}'
  - premiered:
      convert: 'date'
      input_f: '%Y%m%d'
      output_f: '%Y-%m-%d'
      value: '{modified_date}'
